name: build-nightly

on:
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get Time
        run: |
          CURRENT_DATE=$(date +%Y%m%d%H%M%S)
          echo "current_date=$CURRENT_DATE" >> $GITHUB_OUTPUT
      - name: Setup python 3.14t
        uses: actions/setup-python@v6
        with:
            python-version: 3.14t
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build Artifacts
        run: uv build
      - name: Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
            name: "PackWrapper N${{ steps.get_time.outputs.current_date }}"
            tag_name: "nightly"
            token: "${{ secrets.GITHUB_TOKEN }}"
            files: "dist/*"
            prerelease: true