name: build-release

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Setup python 3.14t
        uses: actions/setup-python@v6
        with:
            python-version: 3.14t
      - name: Install UV
        uses: astral-sh/setup-uv@v7
      - name: Build Artifacts
        run: uv build
      - name: Upload Release
        uses: AButler/upload-release-assets@v3.0.1
        with:
          files: "dist/*"
          release-tag: ${{ steps.get_version.outputs.version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}